---
name: Checks

on: [push]

jobs:
  test-Lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker hub
        user: docker/login-action0v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_token}}
      - name: Checkout
        user: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c python manage.py test
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"