---
name: Checks

on: [push]


jobs:
  test-Lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker hub
        uses: docker/login-action0v1
        with:
          username: ${{secrets.MCR92}}
          password: ${{secrets.MCR92_TOKEN}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c python manage.py wait_for_db && python manage.py test
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"